baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown
plugins:
  - jekyll-postcss
  - jekyll-purgecss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - stylelint.config.js
  - netlify.toml
  - bin
  - .gitignore
  - browserslist